# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Setup python 3.8+
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install and lint with black
        if: ${{ always() }}
        run: |
              pip install --upgrade black
              echo ">>> Running black..."
              black --check .

      - name: Install and lint with mypy
        if: ${{ always() }}
        shell: bash
        run: |
              pip install --upgrade mypy
              shopt -s globstar nullglob dotglob
              echo ">>> Running mypy..."
              mypy **/*.py

      - name: Install and lint with pylint
        if: ${{ always() }}
        shell: bash
        run: |
              pip install --upgrade pylint
              shopt -s globstar nullglob dotglob
              echo ">>> Running pylint..."
              pylint **/*.py
      
      - name: Install and lint with pydocsytle
        if: ${{ always() }}
        shell: bash
        run: |
              pip install --upgrade pydocstyle
              echo ">>> Running pydocstyle..."
              pydocstyle .
      
      - name: Install and lint with pycodesytle
        if: ${{ always() }}
        shell: bash
        run: |
              pip install --upgrade pycodestyle
              shopt -s globstar nullglob dotglob
              echo ">>> Running pycodestyle..."
              pycodestyle **/*.py

      - name: Run pytest
        if: ${{ always() }}
        shell: bash
        run: |
              shopt -s globstar nullglob dotglob
              echo ">>> Running pytest..."
              pytest **/*.py
