# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Setup python 3.8+
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install pip
        run: python -m pip install --upgrade pip

      - name: Install and lint with black
        run: |
              pip install --upgrade black
              black --check **/*.py

      - name: Install and lint with mypy
        run: |
              pip install --upgrade mypy
              mypy **/*.py

      - name: Install and lint with pylint
        run: |
              pip install --upgrade pylint
              pylint **/*.py
      
      - name: Install and lint with pycodesytle
        run: |
              pip install --upgrade pycodestyle
              pycodestyle **/*.py
